# 1. Subway

### 1) Split dataset.

<br />
In this part, I split dataset to several CSV files by monthly. In addition to this, I also made a CSV file about an average of years.

As a result of this part, the CSV files are supposed to save at 'csvfiles' folder. The CSV files were in sub-folders by years 2017-2019.

**If you already have the files which is equal to files in the  'csvfiles' folder folder, you don't need to do this part**

Dataset: The average number of passengers on the subway by station and time (monthly) <br />
Link : [The average number of passengers on the subway by station and time](https://data.seoul.go.kr/dataList/datasetView.do?infId=OA-12252&srvType=S&serviceKind=1&currentPageNo=1)

In [26]:
# import Libraries
import pandas as pd
import numpy as np

In [27]:
# read csv file
passenger_monthly = pd.read_csv('passenger_num(subway).csv',encoding = 'utf8')
passenger_monthly

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,201903,분당선,서울숲,53,1,2204,411,5629,8596,15799,...,5631,46,1093,0,0,0,0,0,0,20190403
1,201903,경강선,판교,4,0,446,11,1329,3372,4925,...,693,5,208,0,0,0,0,0,0,20190403
2,201903,경인선,소사,888,32,17219,3318,16507,9045,41632,...,12735,212,3788,0,0,0,0,0,0,20190403
3,201903,9호선,마곡나루,2,0,3865,541,9460,8135,28667,...,11282,812,4184,0,135,0,0,0,0,20190403
4,201903,5호선,여의도,19,0,2508,2683,4423,22762,10975,...,5115,1382,2654,0,0,0,0,0,0,20190403
5,201903,3호선,신사,72,6,5084,1564,7914,21443,14542,...,11996,3814,3911,0,9,0,0,0,0,20190403
6,201903,공항철도 1호선,계양,16,1,9346,712,22917,3393,67586,...,18022,243,4714,0,0,0,0,0,0,20190403
7,201903,경강선,이매,3,0,515,26,1445,647,4835,...,537,17,117,0,0,0,0,0,0,20190403
8,201903,경춘선,상천,0,0,398,4,444,169,673,...,180,1,67,0,0,0,0,0,0,20190403
9,201903,경원선,신이문,1308,5,9135,1570,16049,3184,43743,...,12415,127,3028,0,0,0,0,0,0,20190403
10,201903,경의선,야당,10,0,3322,204,11940,2707,23665,...,5711,274,3596,0,0,0,0,0,0,20190403
11,201903,3호선,을지로3가,8,1,679,996,1440,7963,2409,...,2458,1436,602,0,3,0,0,0,0,20190403
12,201903,6호선,이태원,1,0,15307,1308,12802,7128,16214,...,24187,3661,8461,0,0,0,0,0,0,20190403
13,201903,9호선,공항시장,15,0,2946,422,5036,1324,9279,...,5056,185,1714,0,98,0,0,0,0,20190403
14,201903,8호선,천호(풍납토성),30,0,10944,1858,19315,13639,53160,...,19946,1507,6650,0,283,0,0,0,0,20190403
15,201903,3호선,고속터미널,155,1,6905,4517,8490,38613,31868,...,20323,2906,3314,1,2,1,1,0,0,20190403
16,201903,7호선,상봉(시외버스터미널),397,6,10868,1738,19335,10370,57157,...,21269,1375,8212,0,52,0,0,0,0,20190403
17,201903,2호선,신당,63,1,6680,1322,12672,9834,30731,...,15286,1281,5102,17,180,0,0,0,0,20190403
18,201903,9호선,사평,4,0,754,126,2800,1964,10067,...,3152,121,1113,0,29,0,0,0,0,20190403
19,201903,중앙선,원덕,43,5,290,2,460,74,1280,...,414,3,217,0,0,0,0,0,0,20190403
20,201903,경부선,오산대,47,1,1867,704,4406,2413,12344,...,3956,54,180,0,0,0,0,0,0,20190403
21,201903,중앙선,중랑,65,0,5987,474,9053,2618,25635,...,6215,109,1405,0,0,0,0,0,0,20190403
22,201903,경원선,외대앞,475,2,6263,1710,9638,5018,23033,...,15083,400,3960,0,0,0,0,0,0,20190403
23,201903,7호선,보라매,21,0,6331,2789,7567,9768,21130,...,8459,493,2951,0,82,0,0,0,0,20190403
24,201903,6호선,공덕,150,2,5631,2048,9327,9256,24218,...,12817,1771,5566,1,478,0,0,0,0,20190403
25,201903,7호선,까치울,2,0,3532,846,10240,3984,34298,...,9120,189,2380,0,0,0,0,0,0,20190403
26,201903,5호선,영등포시장,51,0,3022,1225,5675,5611,20401,...,6668,441,1603,0,0,0,0,0,0,20190403
27,201903,경부선,지제,3,0,727,2605,2223,4168,7001,...,1618,2,355,0,0,0,0,0,0,20190403
28,201903,7호선,내방,4,0,2350,1625,7405,10997,19886,...,7793,1104,3745,1,269,0,0,0,0,20190403
29,201903,경인선,주안,917,14,15351,3780,29160,10571,76304,...,28602,1134,8338,0,0,0,0,0,0,20190403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29096,201501,경부선,두정,513,1,3781,837,8019,2357,11378,...,5715,165,2887,0,0,0,0,0,0,20151223
29097,201501,경부선,천안,1413,9,2684,924,6488,3080,11467,...,5245,785,2819,0,0,0,0,0,0,20151223
29098,201501,경부선,서동탄,2,0,729,3,2991,650,7672,...,2212,3,1056,0,0,0,0,0,0,20151223
29099,201501,경부선,광명,0,0,5,2,425,3262,3365,...,0,2,2,0,0,0,0,0,0,20151223
29100,201501,안산선,산본,427,2,9494,1277,26076,4828,62627,...,18559,2173,9778,14,855,0,0,0,0,20151223
29101,201501,안산선,반월,5,1,3008,1027,8950,3546,19074,...,6349,301,2581,0,0,0,0,0,0,20151223
29102,201501,안산선,상록수,234,7,15008,3092,36780,11337,94664,...,28676,1396,14992,0,0,0,0,0,0,20151223
29103,201501,안산선,한대앞,122,3,6343,814,16225,4355,33340,...,10224,611,5092,0,7,0,0,0,0,20151223
29104,201501,안산선,중앙,163,2,7373,706,22930,7575,49986,...,20103,2086,10422,0,42,0,0,0,0,20151223
29105,201501,안산선,고잔,260,2,4504,403,14598,4771,29709,...,11539,485,6359,1,71,0,0,0,0,20151223
29106,201501,3호선,도곡,26,0,1736,437,5756,4650,15284,...,6312,287,3153,1,497,0,0,0,0,20151223
29107,201501,3호선,대치,6,1,2575,917,12157,9574,25605,...,10275,622,3129,14,1,0,0,0,0,20151223
29108,201501,3호선,대청,16,0,3655,1061,11628,5090,31495,...,14388,441,4782,0,1,0,0,0,0,20151223
29109,201501,3호선,일원,4,0,1935,1223,7848,9019,21369,...,7673,209,2329,0,6,0,0,0,0,20151223
29110,201501,3호선,수서,71,1,4399,974,12479,9493,32726,...,13929,335,6515,0,377,0,0,0,0,20151223
29111,201501,3호선,경찰병원,6,1,2336,189,6829,2413,22202,...,8337,218,2194,0,0,0,0,0,0,20151223
29112,201501,3호선,오금,21,0,2830,11,6758,1819,24702,...,9764,150,2976,0,0,0,0,0,0,20151223
29113,201501,4호선,당고개,44,2,9100,14,18211,7518,53191,...,21454,399,7286,2,531,0,0,0,0,20151223
29114,201501,3호선,종로3가,15,0,663,623,1227,3376,1631,...,2627,793,887,2,17,0,0,0,0,20151223
29115,201501,4호선,노원,100,4,11832,654,30613,9336,64281,...,38678,2873,13345,3,377,0,0,0,0,20151223
29116,201501,장항선,온양온천,0,0,1360,827,3567,2702,7492,...,4277,389,1780,0,0,0,0,0,0,20151223
29117,201501,4호선,쌍문,38,0,22176,860,56130,10585,149688,...,53418,987,15401,0,0,1,0,0,0,20151223
29118,201501,4호선,수유(강북구청),76,1,21160,3652,56906,15248,158768,...,63561,2885,15646,1,0,0,0,0,0,20151223
29119,201501,4호선,미아,12,1,10667,1812,23354,5827,64853,...,21422,705,5150,0,0,0,0,0,0,20151223
29120,201501,4호선,미아사거리,26,4,15676,2456,41488,10702,116358,...,41558,2175,9248,3,3,0,0,0,0,20151223
29121,201501,경춘선,남춘천,195,9,1822,33,2779,724,4219,...,3360,5,1550,0,0,0,0,0,0,20151223
29122,201501,장항선,신창,12,0,535,39,1143,355,2087,...,1646,34,755,0,0,0,0,0,0,20151223
29123,201501,3호선,을지로3가,3,0,493,946,975,6878,1679,...,1479,967,394,1,4,0,0,0,0,20151223
29124,201501,경인선,송내,795,10,17163,9249,45504,21530,140677,...,45695,1805,10306,0,0,0,0,0,0,20151223
29125,201501,경춘선,춘천,254,1,527,7,1170,396,2038,...,977,17,1271,0,0,0,0,0,0,20151223

In [28]:
# this part is to chage column names to english

passenger_monthly = passenger_monthly.drop('작업일자',axis=1)
passenger_monthly = passenger_monthly.rename(columns={'사용월' : 'month',
                                                      '호선명' : 'line',
                                                      '지하철역' : 'station'
})
new_col_dict = {}
for i, col in enumerate(passenger_monthly.columns[3:]):
    new_col = col[:2]+'-'+col[4:6]
    
    if i % 2 == 0:
        new_col = new_col + ' (on)'
    else:
        new_col = new_col + ' (off)'
    
    new_col_dict[col] = new_col

passenger_monthly = passenger_monthly.rename(columns=new_col_dict)

In [29]:
# this part is to split 'month' column to 'year' and 'month'

passenger_monthly['year']= passenger_monthly['month']//100
passenger_monthly['month']= passenger_monthly['month']%100
passenger_monthly['month'] = passenger_monthly['month'].astype('int')
columns = passenger_monthly.columns
passenger_monthly = pd.concat([passenger_monthly[columns[-1]],passenger_monthly[columns[:-1]]],axis=1)

In [30]:
passenger_monthly.head()

,year,month,line,station,04-05 (on),04-05 (off),05-06 (on),05-06 (off),06-07 (on),06-07 (off),...,23-24 (on),23-24 (off),00-01 (on),00-01 (off),01-02 (on),01-02 (off),02-03 (on),02-03 (off),03-04 (on),03-04 (off)
0,2019,3,분당선,서울숲,53,1,2204,411,5629,8596,...,1816,5631,46,1093,0,0,0,0,0,0
1,2019,3,경강선,판교,4,0,446,11,1329,3372,...,1858,693,5,208,0,0,0,0,0,0
2,2019,3,경인선,소사,888,32,17219,3318,16507,9045,...,2709,12735,212,3788,0,0,0,0,0,0
3,2019,3,9호선,마곡나루,2,0,3865,541,9460,8135,...,5405,11282,812,4184,0,135,0,0,0,0
4,2019,3,5호선,여의도,19,0,2508,2683,4423,22762,...,12080,5115,1382,2654,0,0,0,0,0,0

In [31]:
# import Libraries
station_location = pd.read_csv('Station_location.csv',sep=',')

In [32]:
# removing columns which we don't need

target_to_remove_list = ['전철역코드','호선','외부코드','사이버스테이션','X좌표','Y좌표']
station_location = station_location.drop(target_to_remove_list,axis=1)

# removing columns which we don't need
station_location  = station_location.rename(columns={'전철역명' : 'station',
                                                     'X좌표(WGS)' : 'X(WGS)',
                                                     'Y좌표(WGS)' : 'Y(WGS)'
                                                     
})

In [33]:
# this dict is about stations which don't have any location information.

missing_station = {}
missing_station['419민주묘지'] = [37.649532, 127.013658]
missing_station['여주'] = [37.282419, 127.628537]
missing_station['가오리'] = [37.641971, 127.016770]
missing_station['북한산보국문'] = [37.612288, 127.008222]
missing_station['북한산우이'] = [37.663155, 127.012767]
missing_station['삼양'] = [37.626962, 127.018148]
missing_station['삼양사거리'] = [37.621334, 127.020489]
missing_station['솔밭공원'] = [37.656098, 127.013227]
missing_station['솔샘'] = [37.620259, 127.013567]
missing_station['정릉'] = [37.602659, 127.013477]
missing_station['화계'] = [37.634111, 127.017493]
missing_station['지평'] = [37.476453, 127.629649]

# put the information at station_location dataframe
for s in missing_station.keys():
    station_location.loc[station_location['station']==s,'X(WGS)'] = missing_station[s][0]
    station_location.loc[station_location['station']==s, 'Y(WGS)']= missing_station[s][1]

In [34]:
def data_spliter(df, year):
    '''
    This function is to split dataframe to CSV files by months and average of the year.
    As a result of this function, we will get CSV files like below:
    1. CSV file about the number of subway passenger by monthly.
     - Passenger information is organized by time as a given csv file, but I add monthly average passenger number.
    2. CSV file about an average number of subway passenger in the specific year.
     - Passenger information is organized by time as a given csv file, and I also add monthly average passenger number.
    
    Args:
    df : target dataframe
    year : num of year which you want to change

    Returns: None
    '''
    dataset = df[df['year']==year]
    month_list = dataset['month'].unique().tolist()
    column_list = dataset.columns.tolist()
    on_list = [columns[s] for s in range(4,len(columns),2)]
    off_list = [columns[s] for s in range(5,len(columns),2)]
    dataset['Total(on)'] = dataset[on_list].sum(axis=1)
    dataset['Total(off)'] = dataset[off_list].sum(axis=1)
    dataset = pd.merge(dataset,station_location,left_on='station',right_on='station')
    output_address1 = 'csvfiles/'+str(year)+'/'
    for month in month_list:
        dataset_monthly = dataset[dataset['month']==month]
        output_address2 = output_address1 + str(month)+'.csv'
        dataset_monthly.to_csv(output_address2,sep=',',index=False)
    average_by_years = dataset.groupby(['line','station'],as_index=False).mean().drop(['month'],axis=1)
    average_by_years.to_csv(output_address1+'average.csv',sep=',',index=False)

In [35]:
import os
for year in range(2015,2020):
    if os.path.isdir('csvfiles/'+str(year)) == False:
        os.mkdir('csvfiles/'+str(year))
    data_spliter(passenger_monthly, year)

C:\Anaconda3\envs\data_basic\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda3\envs\data_basic\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

### 2) Data Visualization (folium).

<br />
This part is to visualize data with folium library.

As a result of this part, html files are supposed to save at 'html(folium)' folder. The html files were in sub-folders by years 2017-2019.

To get location of each station, I will use several dataset which contain station id and location.

Dataset: The subway station id and location <br />
Link : [The subway station id and location](https://data.seoul.go.kr/dataList/datasetView.do?infId=OA-118&srvType=S&serviceKind=1&currentPageNo=1)

In [7]:
import pandas as pd

passenger_num_2019 = pd.read_csv('csvfiles/2019/average.csv',sep=',')

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(pd.DataFrame(passenger_num_2019['total(on)']))

MinMaxScaler(copy=True, feature_range=(0, 1))

In [32]:
import pandas as pd
import folium
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os
target_year_list = [2017,2018,2019]
for year in target_year_list:
    input_file = 'csvfiles/'+str(year)+'/average.csv'
    output_address = 'html(folium)/'+str(year)+'/average.html'
    base_map = folium.Map(location=[37.565822, 126.976880], tiles="Stamen Toner", zoom_start=15)
    passenger_num = pd.read_csv(input_file,sep=',')
    passenger_num['total(on)_scaled'] = scaler.transform(pd.DataFrame(passenger_num['total(on)']))
    station_list = passenger_num['station'].unique().tolist()

    for station in station_list:
        target_ = passenger_num[passenger_num['station']== station]
        X_ = target_['X(WGS)'].tolist()[0]
        Y_ = target_['Y(WGS)'].tolist()[0]
        station_name = station
        line_list = target_['line'].tolist()
        popup_text = '<b>'+station+'</b>' + '&nbsp monthly passenger(on)<br>'
        for line in line_list:
            popup_text += '<span>{} : {}</span><br>'.format(line,int(target_[target_['line']==line]['total(on)']))
        folium.Circle(
                      location=[X_,Y_],
                      radius= np.log1p(target_['total(on)_scaled'].sum())*500,
                      popup = folium.Popup(popup_text,max_width=300),
                      color='crimson',
                      fill=True,
                      fill_color='crimson'
                    ).add_to(base_map)

    if os.path.isdir('html(folium)/'+str(year)) == False:
        os.mkdir('html(folium)/'+str(year))
    base_map.save(output_address)

### 3) Data Visualization (plotly).

<br />
This part is to visualize data with plotly library.

As a result of this part, html files are supposed to save at 'html(plotly)' folder. The html files were in sub-folders by years 2017-2019.

To get location of each station, I will use several dataset which contain station id and location.

Result : https://plot.ly/~s.han/10

Dataset: The subway station id and location <br />
Link : [The subway station id and location](https://data.seoul.go.kr/dataList/datasetView.do?infId=OA-118&srvType=S&serviceKind=1&currentPageNo=1)

In [130]:
import plotly
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

plotly.tools.set_credentials_file(username='##', api_key='##)
mapbox_access_token = '##'
passenger_num_2019 = pd.read_csv('csvfiles/2019/average.csv',sep=',')
scaler = MinMaxScaler()
scaler.fit(pd.DataFrame(passenger_num_2019['total(on)']))

MinMaxScaler(copy=True, feature_range=(0, 1))

In [131]:
(passenger_num_2019[on_list].sum(axis=0)*0).tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [132]:
time_list = passenger_num_2019.columns.tolist()[3:-6]
on_list = [time_list[s] for s in range(0,len(time_list),2)]
on_size_list = [s+' size' for s in on_list]
off_list = [time_list[s] for s in range(1,len(time_list),2)]
off_size_list = [s+' size' for s in off_list]

In [133]:
time_list = [time_list[s][:6] for s in range(0,len(time_list),2)]
time_list.append('Total')

In [134]:
off_size_list

['04-05 (off) size',
 '05-06 (off) size',
 '06-07 (off) size',
 '07-08 (off) size',
 '08-09 (off) size',
 '09-10 (off) size',
 '10-11 (off) size',
 '11-12 (off) size',
 '12-13 (off) size',
 '13-14 (off) size',
 '14-15 (off) size',
 '15-16 (off) size',
 '16-17 (off) size',
 '17-18 (off) size',
 '18-19 (off) size',
 '19-20 (off) size',
 '20-21 (off) size',
 '21-22 (off) size',
 '22-23 (off) size',
 '23-24 (off) size',
 '00-01 (off) size',
 '01-02 (off) size',
 '02-03 (off) size']

In [135]:
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.grid_objs import Grid, Column

station_list = passenger_num_2019['station'].unique().tolist()
lon_list = []
lat_list = []
size_list_on = []
size_list_off = []
for i in range(len(on_list)):
    on_size = on_size_list[i]
    off_size = off_size_list[i]
    passenger_num_2019[on_size] = scaler.transform(pd.DataFrame(passenger_num_2019[on_list[i]]))
    passenger_num_2019[off_size] = scaler.transform(pd.DataFrame(passenger_num_2019[off_list[i]]))

for station in station_list:
    target_ = passenger_num_2019[passenger_num_2019['station']==station]
    lat_list.append(target_['X(WGS)'].tolist()[0])
    lon_list.append(target_[passenger_num_2019['station']==station]['Y(WGS)'].tolist()[0])
    size_list_on.append((target_[on_size_list].sum(axis=0)*500).tolist())
    size_list_off.append((target_[off_size_list].sum(axis=0)*500).tolist())

graph_on = go.Scattermapbox(lat = lat_list,
                            lon = lon_list,
                            mode = 'markers',
                            text = station_list,  
                            hoverinfo = 'text',
                            marker = dict(size = size_list_on[5],
                                          opacity = 0.7,
                                          color = '#2196F3')
                            )

graph_off = go.Scattermapbox(lat = lat_list,
                              lon = lon_list,
                              mode = 'markers',
                              text = station_list, 
                              marker = dict(size = size_list_off[5],
                                            opacity = 0.7,
                                            color = '#F44336')
                            )

data = [graph_on,graph_off]

C:\Users\Han\Anaconda3\envs\data_basic\lib\site-packages\ipykernel_launcher.py:19: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

In [136]:
updatemenus = list([
    dict(type="buttons",
         active = 0,
         buttons=list([
            dict(label ='Both',
                 method='update',
                 args = [{'visible':[True,True]},
                         {'title' : 'Passenger Number (On&Off)'}]),
            dict(label ='On',
                 method='update',
                 args = [{'visible':[True,False]},
                         {'title' : 'Passenger Number (On)'}]),
            dict(label ='Off',
                 method='update',
                 args = [{'visible':[False,True]},
                         {'title' : 'Passenger Number (Off)'}])
         ]),
        direction = 'down',
        pad = {'r': 10, 't': 10}, 
        x = 0.01,
        xanchor = 'left',
        y = 1,
        yanchor = 'top',
        bgcolor = '#AAAAAA',
        bordercolor = '#FFFFFF',
        font = dict(size=11)
        )
])

In [137]:
sliders = dict(active = 0,
               yanchor = 'bottom',
               xanchor = 'right',
               currentvalue = {
                                'font': {'size': 20},
                                'prefix': 'time',
                                'visible': True,
                                'xanchor': 'right'
                            },   
                transition={'duration': 300, 'easing': 'cubic-in-out'},
                pad= {'b': 10, 't': 50},
                len= 0.9,
                x= 0.1,
                y= 0,
                steps= [])

In [138]:
layout = go.Layout(
    title = 'Passenger Number of Subway Station (On&Off)',
    autosize=True,
    showlegend=False,
    hovermode='closest',
    updatemenus=updatemenus,
    sliders=[sliders],
    mapbox=go.layout.Mapbox(
        accesstoken=mapbox_access_token,
        style = 'dark',
        bearing=0,
        center=go.layout.mapbox.Center(

            lat=37.565822,
            lon=126.976880
        ),
        pitch=0,
        zoom=13
    ),
)

In [139]:
fig = go.Figure(data=data, layout=layout)
py.plot(fig,filename='sampleplot.html')

'https://plot.ly/~s.han/12'